#:kivy 1.10.1

<OutPage>:
    name: 'out'
    title: self.name.title()
    SecondaryView:
        id: view
        title: root.title

        AnchorLayout:

            Scanner:
                id: scanner
                play: False

        AnchorLayout:
            PrimaryButton:
                text: "Start"
                size_hint: .4, .4
                on_press:
                    scanner.play = True
